development:
  
      host: localhost
      adapter: postgresql
      database: postgres
      username: postgres
      password: postgres123


test: &test
  
      host: localhost
      adapter: postgresql
      database:  postgres
      username: postgres
      password: postgres123


production:
  
      host: localhost
      adapter: postgresql
      database:  postgres
      username: postgres
      password: postgres123
